---
- name: "Check for the existence of {{ ptq_operator_dir_name }} directory on the quay.io app repository"
  uri:
    url: "https://quay.io/cnr/api/v1/packages/{{ ptq_namespace }}/{{ ptq_operator_dir_name }}"
    headers:
      Authorization: "basic {{ quay_appregistry_api_token }}"
  register: ptq_dir_existence
  failed_when: false

- name: "Delete {{ ptq_operator_dir_name }} from {{ ptq_namespace }} appregistry"
  uri:
    url: "https://quay.io/api/v1/repository/{{ ptq_namespace }}/{{ ptq_operator_dir_name }}"
    method: DELETE
    force_basic_auth: yes
    headers:
      Authorization: "Bearer {{ quay_appregistry_api_token }}"
    status_code: 204
    return_content: yes
