mfbc_dockerfile_path: "{{ pfbc_dockerfile_path }}"
mfbc_extracted_fbc_location: "{{ pfbc_extracted_fbc_location }}"
mfbc_multi_arch_output_image: ""
mfbc_list_architectures_from: "{{ mirror_multiarch_image }}"
container_push_extra: ""
pfbc_extracted_fbc_location: "/tmp/fbc_extracted"
