---
#- name: "Mirroring index image '{{ mi_input_image }}' to mirror location '{{ mi_output_image }}'"
#  block:
#    - name: "Pulling latest input image '{{ mi_input_image }}'"
#      shell: "{{ container_tool }} pull {{ mi_input_image }}"
#
#    - name: "Doing retag of '{{ mi_input_image }}' to '{{ mi_output_image }}'"
#      shell: "{{ container_tool }} tag {{ mi_input_image }} {{ mi_output_image }}"
#
#    - name: "Push image '{{ mi_output_image }}'"
#      shell: "{{ container_tool }} push {{ container_push_extra }} {{ mi_output_image }}"
#  when:
#    - mi_input_image is defined
#    - mi_input_image|length > 0
