- name: "Getting sha from operator bundle version '{{ item }}'"
  shell: "skopeo inspect docker://{{ item }}"
  retries: "{{ default_retries }}"
  delay: "{{ default_delay }}"
  register: bs_skopeo_inspect
  until: bs_skopeo_inspect is not failed

- name: "Reseting bs_skopeo_inspect_info"
  set_fact:
    bs_skopeo_inspect_info: {}

- name: "Settin bs_skopeo_inspect_info"
  set_fact:
    bs_skopeo_inspect_info: "{{ bs_skopeo_inspect.stdout | from_json }}"
  when: bs_skopeo_inspect.rc == 0

- name: "Parsing output image with login information"
  no_log: true
  set_fact:
    bs_bundle: "{{ item.split(':') }}"

- name: "Adding sha as version for {{ item }} "
  set_fact:
    bob_bundles_sha_arr: "{{ bob_bundles_sha_arr | default([]) }} + [ '{{ bs_bundle[0] }}@{{ bs_skopeo_inspect_info.Digest }}' ]"
  when:
    - bs_skopeo_inspect_info.Digest is defined
    - bs_skopeo_inspect_info.Digest|length > 0
    - (item|regex_findall(':')|length) == 1

- name: "Adding sha as version for {{ item }} when registry with port "
  set_fact:
    bob_bundles_sha_arr: "{{ bob_bundles_sha_arr | default([]) }} + [ '{{ bs_bundle[0] }}:{{ bs_bundle[1] }}@{{ bs_skopeo_inspect_info.Digest }}' ]"
  when:
    - bs_skopeo_inspect_info.Digest is defined
    - bs_skopeo_inspect_info.Digest|length > 0
    - (item|regex_findall(':')|length) == 2
