pfbc_file_index: ""
pfbc_extracted_fbc_location: "/tmp/fbc_extracted"
pfbc_operator_yaml_location: "configs"
pfbc_index_update: false
pfbc_render_from: "index"
pfbc_sql_index: ""
bundle_index_fbc_postfix: "f"
pfbc_multi_arch_input_image: "{{ pfbc_file_index }}"
pfbc_multi_arch_output_image: ""
pfbc_actual_fbc_arch_image: ""
pfbc_local_cache_dir: "/tmp/cache"
