---
- name: "Remove any previous courier results"
  shell: "rm -f {{ work_dir }}/linting-results.json"

- name: "Output the operator-courier version"
  shell: "operator-courier -v"
  register: courier_version_result

- name: "Output the operator-courier version to a debug file"
  copy:
    content: "{{ courier_version_result.stdout }}"
    dest: "{{ work_dir }}/linting-version.txt"
  when: courier_version_result.stdout is defined

- name: "Verify the operator metadata with operator-courier"
  shell: "operator-courier verify {{ operator_work_dir }} --ui_validate_io --validation-output {{ work_dir}}/linting-results.json > {{ work_dir}}/linting-output.txt 2> {{ work_dir}}/linting-errors.txt"
  register: courier_verify_result
  ignore_errors: true

- name: "Output the return code of operator-courier verify command to a debug file"
  copy:
    content: "{{ courier_verify_result.rc }}"
    dest: "{{ work_dir }}/linting-rc.txt"
  when: courier_verify_result.rc is defined

- name: "Fail if the operator didn't satisfy the operator courier verification test"
  fail:
    msg: 'Operator courier verification test failed, check linting-errors.txt for more details'
  when:
    - check_verify_result|bool
    - courier_verify_result.rc != 0
    - not run_upstream|bool
    - permisive is not defined or not permisive|bool

- name: "Handle permisive mode when operator is failing to deploy on kind cluster"
  set_fact:
    test_all_add_failed_name_version_validation: "{{ test_all_add_failed_name_version_validation | default([]) }} + [ '{{ operator_name }}:{{ operator_version }}' ]"
  when:
    - permisive is defined
    - permisive|bool
    - courier_verify_result.rc != 0
    - run_upstream|bool
