opm_container_tool: "docker"
container_tool: "docker"
container_push_extra: ""
work_dir: "/tmp/operator-test"
testing_bin_path: "{{ work_dir }}/bin"
jq_bin_path: "{{ testing_bin_path }}/jq"
mirror_input_image: "kind-registry:5000/test-operator/catalog"
mirror_index_images: "kind-registry:5000/test-operator/catalog_mirror_auth|user|password,kind-registry:5000/test-operator/catalog_mirror_no_auth"
iib_base_url: http://localhost:8080
iib_url_options: ""
iib_input_local_host_image_base: kind-registry:8443/test-operator/catalog:latest
iib_input_local_worker_image_base: registry:8443/test-operator/catalog:latest
iib_converted_image_base: registry:8443/iib-build
mi_tmp_postfix: "_tmp"
#nonprod_sha_postfix: "s"
#nonprod_fbc_postfix: "sf"
nonprod_postfix: "fbc"
nonprod_index_image_name: "catalog"
mi_another_iib_needed: false
mi_input_index_already_set: false
mi_sql_mirror_input_default: "{{ bundle_registry }}/{{ bundle_index_image_namespace }}/catalog:latest"
ms_index_prod_location: "{{ ms_info[4] }}"
