operator_bundle_src_dir: /tmp/operator-test/operator-bundle/src
operator_name: ""
operator_version: latest
opm_container_tool: "docker"
bundle_registry: localhost:5000
bundle_image_namespace: test-operator
bundle_index_image_namespace: test-operator
bundle_index_image_name: "index"
bundle_index_image_version: "latest"
operators_for_index: []
opm_index_add_extra_args: ""