---
- name: "Debug"
  debug:
    var: doic_final_list

- name: "Debug"
  debug:
    var: doic_versions_from_bundle

- name: "Task #5: Adding current {{ doic_supported_index_from_api_parsed_version }} to target {{ dov_cluster_ver }}"
  set_fact:
    doic_final_list: "{{ (doic_final_list | default([])) + [doic_versions_from_bundle] }}"
  when:
    - doic_versions_from_bundle is defined
    - doic_versions_from_bundle | length > 0

- name: "Task #5: Adding current {{ doic_supported_index_from_api_parsed_version }} to target {{ dov_cluster_ver }}"
  set_fact:
    doic_final_list_bundles: "{{ (doic_final_list_bundles | default([])) + [lc_doic_bundles_processing] }}"


- name: "Adding versions in prod"
  set_fact:
    doic_final_list_versions_prod: "{{ (doic_final_list_versions_prod | default([])) + [doic_versions_from_bundle] }}"
  when:
    - not lc_doic_bundles_processing.startswith('kind-registry')
    - doic_versions_from_bundle is defined
    - doic_versions_from_bundle | length > 0
