operator_input_local_registry: "kind-registry:5000"
bundle_input_tmp_dir:  "{{ work_dir }}/operator-bundle-input/tmp"
bundle_input_src_dir:  "{{ work_dir }}/operator-bundle-input/src"
opm_container_tool: docker