validate_api: true
#validate_label: false
validate_label: true
bvf_supported_cluster_versions:
  - "4.6"
  - "4.7"
  - "4.8"
  - "4.9"
  - "4.10"
  - "4.11"
  - "4.12"
  - "4.13"
operator_sdk_bin_path: "{{ testing_bin_path }}/operator-sdk"
testable_k8s_clusters:
  # This is the list of k8s versions that deprecate old apis
  - "1.22"
k8s2ocp:
  "1.13": "4.0"
  "1.14": "4.1"
  "1.15": "4.2"
  "1.16": "4.3"
  "1.17": "4.4"
  "1.18": "4.5"
  "1.19": "4.6"
  "1.20": "4.7"
  "1.21": "4.8"
  "1.22": "4.9"
  "1.23": "4.10"
  "1.24": "4.11"
  "1.25": "4.12"
  "1.26": "4.13"
ocp2k8s:
  "4.0": "1.13"
  "4.1": "1.14"
  "4.2": "1.15"
  "4.3": "1.16"
  "4.4": "1.17"
  "4.5": "1.18"
  "4.6": "1.19"
  "4.7": "1.20"
  "4.8": "1.21"
  "4.9": "1.22"
  "4.10": "1.23"
  "4.11": "1.24"
  "4.12": "1.25"
  "4.13": "1.26"
