- name: "Setting operator dir name"
  set_fact:
    operator_dir_name: "{{ operator_dir | basename }}"

- name: "Remove repo '{{ bundle_index_image_namespace }}/{{ operator_dir_name }}' from 'quay'"
  uri:
    url: "{{ registry_api_http_protocol | default('https') }}://quay.io/api/v1/repository/{{ bundle_index_image_namespace }}/{{ operator_dir_name }}"
    method: DELETE
    force_basic_auth: yes
    headers:
      Authorization: "Bearer {{ quay_api_token }}"
    status_code: 204
  failed_when: false
  when:
    - quay_api_token is defined
    - quay_api_token != ""

- name: "Setting bundle image name"
  set_fact:
    bundle_index_image: "{{ bundle_registry }}/{{ bundle_index_image_namespace }}/{{ bundle_index_image_name }}:{{ bundle_index_image_version }}"
    opm_index_add_extra_args: "--from-index {{ bundle_registry }}/{{ bundle_index_image_namespace }}/{{ bundle_index_image_name }}:{{ bundle_index_image_version }}"

- name: "Remove operator '{{ operator_dir_name }}' from index image {{ bundle_index_image }}"
  shell: "{{ opm_bin_path }} index rm  -c {{ opm_container_tool }} --operators {{ operator_dir_name }} --tag {{ bundle_index_image }}  {{ opm_index_add_extra_args }}"
  failed_when: false

- name: Push bundle image {{ bundle_index_image }}
  shell: "{{ opm_container_tool }} push {{ bundle_index_image }}"
  failed_when: false

- name: "Remove temporary bundle export dir '{{ bundle_export_dir_remove }}'"
  file:
    path: "{{ bundle_export_dir_remove }}"
    state: absent

- name: "Trying to export operator '{{ operator_dir_name }}' from index image {{ bundle_index_image }}"
  shell: "{{ opm_bin_path }} index export -c {{ opm_container_tool }} --package {{ operator_dir_name }} --index {{ bundle_index_image }} --download-folder {{ bundle_export_dir_remove }}"
  register: rob_export_rc

- name: "Search for all operators '{{ bundle_export_dir_remove }}'"
  find:
    paths: "{{ bundle_export_dir_remove }}"
    recurse: no
    file_type: directory
  register: rob_operators_find

- name: "Fail when export works after removal of operator '{{ operator_dir_name }}' from index image {{ bundle_index_image }}"
  fail:
    msg: "Operator '{{ operator_dir_name }}' was not correctly removed from {{ bundle_index_image }} !!! Look in exported directory '{{ bundle_export_dir_remove }}' on remote host for more info."
  when: rob_operators_find.files.0 is defined

- name: "Setting operator was removed"
  set_fact:
    operator_removed: true

# - meta: end_play
