---
- set_fact:
    bundle_index_image: "{{ bundle_index_registry }}/{{ bundle_index_image_namespace }}/{{ operator_name }}-{{ bundle_image_suffix }}:v{{ operator_version }}"

- name: Remove index image {{ bundle_index_image }}
  shell: "{{ opm_container_tool }} rmi -f {{ bundle_index_image }}"

- name: Build index image {{ bundle_index_image }}
  shell: "{{ opm_bin_path }} index add -d {{ bundle_db }} -u {{ opm_container_tool }} --bundles {{ bundle_image }} --tag {{ bundle_index_image }} --skip-tls"

- name: Push bundle image {{ bundle_index_image }}
  shell: "{{ opm_container_tool }} push {{ bundle_index_image }}"
