opm_bin_path: "{{ testing_bin_path }}/opm"
container_tool: "docker"
opm_container_tool: "docker"
opm_container_tool_index: "docker"
bundle_registry: "quay.io"
ptq_namespace: "community-operators"
ptq_operator_dir_name: "{{ operator_dir | basename }}"
ptq_download_folder: "/tmp/quay_push_dir"
ptq_index_args: ""
bundle_index_image_namespace: test-operator
bundle_index_image_name: "catalog"
bundle_index_image_version: "latest"
bundle_index_image: "{{ bundle_registry }}/{{ bundle_index_image_namespace }}/{{ bundle_index_image_name }}:{{ bundle_index_image_version }}"
ptq_cluster_version_support: false
