---
oc_bin_path: "{{ '/snap/bin/kubectl' if (distro_type == 'upstream') else 'oc' }}"
olm_operator_files_path: "{{ playbook_dir }}/../../operators/olm-operator-files"
openshift_namespace: test-operator