---

- name: "Uninstall kind binary"
  file:
    path: "{{ kind_bin_path }}"
    state: absent
  become: yes
  tags:
    - never
    - uninstall

- name: "Ensure kind binary is installed"
  block:
    - name: "Check that the kind executable exists"
      stat:
        path: "{{ kind_bin_path }}"
      register: rc_kind

    - name: "Install kind binary"
      get_url:
        url: "https://github.com/kubernetes-sigs/kind/releases/download/{{ kind_version }}/kind-linux-amd64"
        dest: "{{ kind_bin_path }}"
        mode: '0755'
      register: kind_install_result
      until: kind_install_result.status_code is undefined or kind_install_result.status_code == 200
      retries: 10
      delay: 15
      failed_when: kind_install_result is failure
      become: yes
      when: rc_kind.stat.exists == false
  tags:
    - reset
    - install
    - host_build

- name: "Ensure operator-sdk binary is installed"
  block:
    - name: "Make sure that '{{ testing_bin_path }}' exists"
      file:
        path: "{{ testing_bin_path }}"
        state: directory
      tags:
        - install
        - host_build
        - reset_tools

    - name: "Remove '{{ operator_sdk_bin_path }}' binary"
      file:
        path: "{{ operator_sdk_bin_path }}"
        state: absent
      tags:
        - install
        - uninstall
        - reset_tools

    - name: "Install operator-sdk"
      get_url:
        url: https://github.com/operator-framework/operator-sdk/releases/download/{{ operator_sdk_version }}/operator-sdk-{{ operator_sdk_version }}-x86_64-linux-gnu
        dest: "{{ operator_sdk_bin_path }}"
        mode: "0755"
      register: operator_sdk_install_result
      until: operator_sdk_install_result.status_code is undefined or operator_sdk_install_result.status_code == 200
      retries: 10
      delay: 15
      failed_when: operator_sdk_install_result is failure
      tags:
        - install
        - host_build
        - reset_tools


- name: "Reset Kind with registry"
  include_role:
    name: reset_kind
  tags:
    - reset
    - install
    - host_build
