jq_bin_path: jq
yq_bin_path: yq
skopeo_bin_path: skopeo
image_protocol: "docker://"
operator_work_dir: /home/jenkins/agent/test-operator
bundle_sanity_checks: true
required_labels:
  - 'operators.operatorframework.io.bundle.package.v1'
  - 'operators.operatorframework.io.bundle.channels.v1'
  - 'com.redhat.openshift.versions'
