---
- name: "Print"
  debug:
    msg: "Running  '{{ oi_operator_name }}:{{ oiiv_version_item }}' for index '{{ oii_index_version }}'"

- name: "Filtering index add versions"
  set_fact:
    oii_index: "{{ (oii_index | default([])) + [ oiiv_version_item ] }}"
  when: oii_index_version is in io_versions_manifests[oiiv_version_item].idx_versions

# - name: "Filtering deprecate truncate versions"
#   set_fact:
#     oii_index_dt: "{{ (oii_index_dt | default([])) + [ oiiv_version_item ] }}"
#   when:
#     - oii_index_version is in io_versions_manifests[oiiv_version_item].idx_user_label_versions
#     - oii_index_version not in io_versions_manifests[oiiv_version_item].idx_versions
