operator_info_output_file: "{{ work_dir }}/op_info.yaml"
op_info_parallel_batch: 10
oi_auto_labels_output_file: "{{ work_dir }}/op_auto_labels.yaml"
operator_bundle_src_dir: "{{ work_dir }}/operators"
oi_failed_labels_output_file: "{{ work_dir }}/op_failed_labels.yaml"
oi_failed_k8s_bundles_output_file: "{{ work_dir }}/op_failed_k8s_bundles.yaml"
automatic_cluster_version_label: false
strict_k8s_bundles: false
strict_cluster_version_labels: false
ignore_image_string: "--"
format_failed_file: "{{ work_dir }}/format_failed"
ocp2k8s:
  "4.0": "1.13"
  "4.1": "1.14"
  "4.2": "1.15"
  "4.3": "1.16"
  "4.4": "1.17"
  "4.5": "1.18"
  "4.6": "1.19"
  "4.7": "1.20"
  "4.8": "1.21"
  "4.9": "1.22"
  "4.10": "1.23"
  "4.11": "1.24"
  "4.12": "1.25"
  "4.13": "1.26"
  "4.14": "1.27"
  "4.15": "1.28"
  "4.16": "1.29"
oi_supported_cluster_versions:
  - "4.10"
  - "4.11"
  - "4.12"
  - "4.13"
  - "4.14"
  - "4.15"
