operator_bundle_src_dir: /tmp/operator-test/operator-bundle/src
# operator_name: ""
operator_version: latest
opm_container_tool: "docker"
bundle_image_namespace: test-operator
bundle_registry: localhost:5000