---
- name: "Delete kind cluster (Wait until success)"
  block:
    - name: Set the retry count
      set_fact:
        delete_kind_retry_count: "{{ 2 if delete_kind_retry_count is undefined else delete_kind_retry_count|int + 1 }}"

    - name: "Check that the kind executable exists"
      stat:
        path: "{{ kind_bin_path }}"
      register: rc_kind

    - name: "Delete kind cluster"
      shell: "kind delete cluster --name {{ kind_cluster_name }}"
      when: rc_kind.stat.exists

    - name: "Destroy current kind registry"
      shell: "docker rm -f kind-registry"
      failed_when: false

    - name: "Installing Kind with registry"
      block:
        - name: "Generating file for kind and registry"
          template:
            src: kind-with-registry.sh.j2
            dest: "{{ kind_tmp_dir }}/kind-with-registry.sh"
            mode: '0755'

        - name: "Configuring Kind with registry"
          shell: "{{ kind_tmp_dir }}/kind-with-registry.sh"
      when: rc_kind.stat.exists

    - name: "Make sure that '{{ testing_bin_path }}' exists"
      file:
        path: "{{ testing_bin_path }}"
        state: directory

    - name: "Check if operator-sdk exists"
      stat:
        path: "{{ operator_sdk_bin_path }}"
      register: rkr_osdk

    - name: "Install operator-sdk"
      get_url:
        url: https://github.com/operator-framework/operator-sdk/releases/download/{{ operator_sdk_version }}/operator-sdk-{{ operator_sdk_version }}-x86_64-linux-gnu
        dest: "{{ operator_sdk_bin_path }}"
        mode: "0755"
      register: operator_sdk_install_result
      until: operator_sdk_install_result.status_code is undefined or operator_sdk_install_result.status_code == 200
      retries: 10
      delay: 15
      failed_when: operator_sdk_install_result is failure
      when:
       - not rkr_osdk.stat.exists
       - not run_upstream|bool

    - name: "Install operator-sdk"
      get_url:
        url: https://github.com/operator-framework/operator-sdk/releases/download/{{ operator_sdk_version }}/operator-sdk_linux_amd64
        dest: "{{ operator_sdk_bin_path }}"
        mode: "0755"
      register: operator_sdk_install_result
      until: operator_sdk_install_result.status_code is undefined or operator_sdk_install_result.status_code == 200
      retries: 10
      delay: 15
      failed_when: operator_sdk_install_result is failure
      when:
       - not rkr_osdk.stat.exists
       - run_upstream|bool

    - name: "Installing OLM ({{ olm_version }})"
      shell: "{{ operator_sdk_bin_path }} olm install --version {{ olm_version }} --timeout 5m0s"
      register: olm_install_rc
  tags:
    - always
  rescue:
    - fail:
        msg: Ended after 5 retries
      when: delete_kind_retry_count|int > 5

    - debug:
        msg: "Failed to connect - Retrying ({{ delete_kind_retry_count }}/5) ..."

    - include_tasks: reset.yml
