operator_bundle_src_dir: "/tmp/operator-test/operators"
operator_name: ""
operators_for_index: []
bundle_registry: kind-registry:5000
bundle_image_namespace: test-operator
supported_cluster_versions: "dummy"
ignore_image_string: "--"
default_retries: 5
default_delay: 10
