---
- name: "Read the variables from annotations.yaml"
  include_vars:
    file: "{{ operator_work_dir }}/metadata/annotations.yaml"
    name: annotations_vars
  when: not run_upstream|bool

- name: "Read the variables from annotations.yaml"
  block:
    - shell: cat "{{ operator_work_dir }}/metadata/annotations.yaml"
      register: annotation_data
    - name: Debug
      debug:
        msg: "{{ annotation_data.stdout | from_yaml }}"
    - name: Set facts
      set_fact:
        annotations_vars: "{{ annotation_data.stdout | from_yaml }}"
  when: run_upstream|bool

- debug:
    var: skopeo_inspect_json.Labels

- debug:
    var: annotations_vars.annotations

- name: "Check if the operators.operatorframework.io.bundle.channel.default.v1 from annotation.yaml matches the bundle image label"
  fail:
    msg: "The operators.operatorframework.io.bundle.channel.default.v1 value in the annotations yaml doesn't match the corresponding bundle image label!"
  when:
    - annotations_vars.annotations['operators.operatorframework.io.bundle.channel.default.v1'] != skopeo_inspect_json.Labels['operators.operatorframework.io.bundle.channel.default.v1']

- name: "Check if the operators.operatorframework.io.bundle.channels.v1 from annotation.yaml matches the bundle image label"
  fail:
    msg: "The operators.operators.operatorframework.io.bundle.channels.v1 value in the annotations yaml doesn't match the corresponding bundle image label!"
  when:
    - annotations_vars.annotations['operators.operatorframework.io.bundle.channels.v1'] != skopeo_inspect_json.Labels['operators.operatorframework.io.bundle.channels.v1']

- name: "Check if the operators.operatorframework.io.bundle.manifests.v1 from annotation.yaml matches the bundle image label"
  fail:
    msg: "The operators.operators.operatorframework.io.bundle.manifests.v1 value in the annotations yaml doesn't match the corresponding bundle image label!"
  when:
    - annotations_vars.annotations['operators.operatorframework.io.bundle.manifests.v1'] != skopeo_inspect_json.Labels['operators.operatorframework.io.bundle.manifests.v1']

- name: "Check if the operators.operatorframework.io.bundle.mediatype.v1 from annotation.yaml matches the bundle image label"
  fail:
    msg: "The operators.operatorframework.io.bundle.mediatype.v1 value in the annotations yaml doesn't match the corresponding bundle image label!"
  when:
    - annotations_vars.annotations['operators.operatorframework.io.bundle.mediatype.v1'] != skopeo_inspect_json.Labels['operators.operatorframework.io.bundle.mediatype.v1']

- name: "Check if the operators.operatorframework.io.bundle.mediatype.v1 is set to the expected value"
  fail:
    msg: "The operators.operatorframework.io.bundle.mediatype.v1 value doesn't match the expected value \"{{ label_mediatype_v1_expected_value }}\""
  when:
    - annotations_vars.annotations['operators.operatorframework.io.bundle.mediatype.v1'] != label_mediatype_v1_expected_value

- name: "Check if the operators.operatorframework.io.bundle.metadata.v1 from annotation.yaml matches the bundle image label"
  fail:
    msg: "The operators.operatorframework.io.bundle.metadata.v1 value in the annotations yaml doesn't match the corresponding bundle image label!!"
  when:
    - annotations_vars.annotations['operators.operatorframework.io.bundle.metadata.v1'] != skopeo_inspect_json.Labels['operators.operatorframework.io.bundle.metadata.v1']

- name: "Check if the operators.operatorframework.io.bundle.package.v1 from annotation.yaml matches the bundle image label"
  fail:
    msg: "The operators.operatorframework.io.bundle.package.v1 value in the annotations yaml doesn't match the corresponding bundle image label!"
  when:
    - annotations_vars.annotations['operators.operatorframework.io.bundle.package.v1'] != skopeo_inspect_json.Labels['operators.operatorframework.io.bundle.package.v1']
