# This is a basic workflow to help you get started with Actions

name: Build playbook image

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  # pull_request:
    # branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  playbook_image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_PLAYBOOK_IMAGE_USERNAME }}
          password: ${{ secrets.QUAY_PLAYBOOK_IMAGE_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          #context: .
          #file: Dockerfile
          push: true
          tags: quay.io/operator_testing/operator-test-playbooks:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
