name: Build playbook image

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  playbook_image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_PLAYBOOK_IMAGE_USERNAME }}
          password: ${{ secrets.QUAY_PLAYBOOK_IMAGE_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate version for playbook image
        id: playbook-image-version
        run: ./upstream/playbook_version.sh
      - name: Print version
        run: echo "Image version is ${{ steps.playbook-image-version.outputs.image_version }}"
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: quay.io/operator_testing/operator-test-playbooks:${{ steps.playbook-image-version.outputs.image_version }},quay.io/operator_testing/operator-test-playbooks:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
